#!name=YouTube Enhance (Egern)
#!desc=移除 YouTube 广告，启用画中画/后台播放，并强制最高画质。派生自 Maasea (Apache-2.0)。
#!category=Streaming
#!arguments=block_upload:true,block_shorts:false,auto_hd:true,block_games:true,block_vertical_live:false
#!arguments-desc=block_upload: 隐藏底部上传按钮; block_shorts: 隐藏 Shorts; auto_hd: 强制最高画质; block_games: 隐藏 Playables 小游戏; block_vertical_live: 隐藏竖屏直播推荐流。

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com),(PROTOCOL,QUIC)),REJECT
AND,((DOMAIN-SUFFIX,youtubei.googleapis.com),(PROTOCOL,QUIC)),REJECT

[Script]
youtube.enhance.ad-break = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/player\/ad_break(?:\?.*)?$,script-path=https://raw.githubusercontent.com/Siu-Leung/surge-youtube-enhance/main/scripts/youtube/request.js
youtube.enhance.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(?:navigation\/resolve_url|browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch|log_event|config)(?:\?.*)?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Siu-Leung/surge-youtube-enhance/main/scripts/youtube/response.js,argument="{"blockUpload":{{{block_upload}}},"blockShorts":{{{block_shorts}}},"blockGames":{{{block_games}}},"blockVerticalLive":{{{block_vertical_live}}}}"
youtube.enhance.ump = type=http-response,pattern=^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback(?:\?.*)?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Siu-Leung/surge-youtube-enhance/main/scripts/youtube/response.js,argument="{"blockGames":{{{block_games}}},"blockVerticalLive":{{{block_vertical_live}}}}"
youtube.enhance.init = type=http-request,pattern=^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback(?:\?.*)?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Siu-Leung/surge-youtube-enhance/main/scripts/youtube/request.js
youtube.enhance.auto-hd = type=http-request,pattern=^https?:\/\/[\w-]+\.googlevideo\.com\/videoplayback,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Siu-Leung/surge-youtube-enhance/main/scripts/youtube/request.js,argument="{"autoHd":{{{auto_hd}}}}"
youtube.enhance.log-event = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/log_event,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Siu-Leung/surge-youtube-enhance/main/scripts/youtube/request.js

[URL Rewrite]
^https:\/\/www\.youtube\.com\/(pagead|pcs)\/ - reject
^https:\/\/s\.youtube\.com\/api\/stats\/ads - reject

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com, *.youtube.com
